name: Onyx
version: 0.3
author: PluginSupport
main: support.plugin.onyx.Onyx
description: A free, open source Hardcore Factions core using Redis. Copyright (c) 2017 PluginManager LTD. All rights reserved.